create database OUTLET; --- CREAZIONE DATABASE
---CREAZIONE TABELLA STORE E REGIONI
CREATE TABLE STORE (
					NAMEID INT AUTO_INCREMENT PRIMARY KEY, 
					NOME VARCHAR(60),
					CITTA VARCHAR(60),
					CAP VARCHAR(10),
					REGIONE VARCHAR(60),
					AREAGEOGRAFICA VARCHAR(60),
					PAESE VARCHAR(10)
);

CREATE TABLE REGIONI (
					REGIONEID INT AUTO_INCREMENT PRIMARY KEY,
                    NOMEREGIONE VARCHAR(60),
                    CITTA VARCHAR(60),
                    AREAGEOGRAFICA VARCHAR(60),
                    CAP VARCHAR(10),
                    PAESE VARCHAR(20)
);

----INSERIMENTO ATTRIBUTI NELL ENTITA STORE E REGIORNI

INSERT INTO STORE (NOME,CITTA,CAP,REGIONE,AREAGEOGRAFICA,PAESE)
VALUES			('SCALO MILANO','MILANO','20092','LOMBARDIA','NORD','ITALIA'),
                ('SERRAVALLE OUTLET','SERRAVALLE SCRIVIA','15069','PIEMONTE','NORD OVEST','ITALIA'),
                ('VALMONTONE OUTLET','VALMONTONE','00038','LAZIO','CENTRO','ITALIA'),
                ('SICILIA OUTLET VILLAGE','ENNA','94011','SICILIA','SUD','ITALIA'),
                ('NOVENTA DI PIAVE DESIGNER','NOVENTA DI PIAVE','30020','VENETO','NORD EST','ITALIA');


INSERT INTO REGIONI (NOMEREGIONE,CITTA,AREAGEOGRAFICA,CAP,PAESE)
VALUES 				('LOMBARDIA','MILANO','NORD','20092','ITALIA'),
                    ('PIEMONTE','SERRAVALLE SCRIVIA','NORD EST','15069','ITALIA'),
                    ('LAZIO','VALMONTONE','CENTRO','00038','ITALIA'),
                    ('SICILIA','ENNA','SUD','94011','ITALIA'),
                    ('VENETO','NOVENTA DI PIAVE','NORD EST','30030','ITALIA');

SELECT *
FROM STORE;
SELECT *
FROM REGIONI;

UPDATE REGIONI
SET AREAGEOGRAFICA = 'NORD OVEST'
WHERE REGIONEID = 2;

---INSERISCO UN NUOVO ATTRIBUTO NELL ENTITA 'STORE'
INSERT INTO STORE (NOME, CITTA, CAP, REGIONE, AREAGEOGRAFICA, PAESE)
VALUES ('Store Roma Centro', 'Roma', '00100', 'Lazio', 'Centro ', 'Italia');

INSERT INTO REGIONI (NOMEREGIONE,CITTA,AREAGEOGRAFICA,CAP,PAESE)
VALUES 				('PUGLIA','BARI','SUD','80100','ITALIA');


DELETE FROM STORE
WHERE NAMEID = 3;

DELETE FROM STORE
WHERE CITTA=3;

DELETE FROM REGIONI ----- ELIMINO DALLA TABELLA REGIONI IL NOME DELLA CITTA CHE SI TROVA SUL RECORD NUMERO 2
WHERE CITTA=2;

DELETE FROM REGIONI; --- SVUOTO LA TABELLA MA MANTEGO LA STRUTTURA



